version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - echo "Installing PDM..."
      - pip install --user pdm
    post_create_environment:
      - export PATH="/home/docs/.local/bin:$PATH"
      - pdm install --dev --group docs

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs